services:
    ui:
        build:
            context: ./ui
            dockerfile: ./Dockerfile
        volumes:
            - ./ui:/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - esnet
        ports:
            - "80:80"
        develop:
            watch:
                - action: rebuild
                  path: ./ui

    core:
        build:
            context: ./core
            dockerfile: ./Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - elasticsearch
        networks:
            - esnet
        links:
            - elasticsearch
        develop:
            watch:
                - action: rebuild
                  path: ./core

    elasticsearch:
        image: elasticsearch:8.16.1
        ports:
            - "9200:9200"
        environment:
            - discovery.type=single-node # testing env
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - xpack.security.enabled=true
            - ELASTIC_PASSWORD=new_password
        volumes:
            - esdata:/usr/share/elasticsearch/data
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9200/"]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - esnet

volumes:
    esdata:  # volume for elasticsearch data
networks:
    esnet: