services:
    ui:
        build:
            context: ./ui
            dockerfile: ./Dockerfile
        volumes:
            - ./ui:/app
        ports:
            - "8080:80"

    core:
        build:
            context: ./core
            dockerfile: ./Dockerfile
        volumes:
            - ./core:/app
        ports:
            - "8000:8000"
        depends_on:
            - elasticsearch

    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - ui
            - core

    elasticsearch:
        image: elasticsearch:8.16.1
        ports:
            - "9200:9200"
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - xpack.security.enabled=true
            - ELASTIC_PASSWORD=new_password
        volumes:
            - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:  # Define a volume for Elasticsearch data